services:
  api:
    build: .
    container_name: vantrack_api
    # Fica em sleep infinitamente (esperando launch do vscode)
    command: sleep infinity
    volumes:
      - .:/code
      - pre-commit-cache:/root/.cache/pre-commit
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env

  # Serviço auxiliar para rodar o Ruff de forma isolada
  lint:
    build: .
    container_name: vantrack_lint
    volumes:
      - .:/code
    command: ruff check . --watch # Fica vigiando mudanças e avisa erros de tipagem

volumes:
  pre-commit-cache:
